### ISSUE TITLE
Access to AppData\Local\Temp\Clowd.Squirrel\temp.2 is denied

### ISSUE THREAD

**Issue by jokyjoey** [clowd/Clowd.Squirrel#119] opened 2022-09-13 05:24 UTC
Hi!

When installing my application the installation sometimes fails with the error in the following screenshot. According to the stacktrace it tries to extract the content of the package into a temporary folder but fails to access it.

![grafik](https://user-images.githubusercontent.com/5881524/189814029-a8f09984-e4b2-4159-b465-983d56d3b4d1.png)

I'm currently using the 3.0.210-g5f9f594 preview and I'm not entirely sure if this is a bug in Squirrel at all, but just me doing something wrong (or something else getting in the way).

Has anyone else also encountered this issue and knows how to fix this?

**Comment by caesay** [comment] 2022-09-14 18:10
Hi there! you say it sometimes fails. How reproducible is this? Are you using any anti-virus software? If it's fairly reproducible and you are using AV, can you temporarily turn off your anti-virus and see if the issue still occurs?

**Comment by caesay** [comment] 2022-09-15 11:28
Are these machines joined to an active directory domain? Or have any group policies been set that might impact the system temp directory? 

And have you only seen this with installing, or does it happen when Updating too?

**Comment by jokyjoey** [comment] 2022-09-15 11:56
Yes the machines are indeed joined to a domain, but there are no GPOs regarding the temp directory.

The issue only occurs when doing an installation by executing the Setup.exe. Updates via the app itself (via UpdateManager) always work.

**Comment by jokyjoey** [comment] 2022-09-21 05:46
Having executed the Setup.exe over a hundred times in a row now, while also watching the Clowd.Squirrel\temp.x folders, as well as the target folder. I'm still not completely sure, but for me it seems as the reason must be some kind of timing or thread blocking/overlap/order issue.

In these cases when I get the error, I can see the **temp.1** and **temp.2** are created and populated correctly, but the **output directory (outFinalFolder)** is either missing some of the files or is completely empty. 

It looks like that the temporary **temp.2** folder is already deleted, when the following line is executed:

https://github.com/clowd/Clowd.Squirrel/blob/5f9f594b3d20453652fde782800d9293914db44e/src/Squirrel/NuGet/ZipPackage.cs#L225

**Comment by caesay** [comment] 2022-09-21 08:52
Thanks for the detailed investigation. If you don't find the issue before me, I will step through the installer at some point soon and look for potential problems.

**Comment by jokyjoey** [comment] 2022-09-21 13:22
I just cloned the source code and did several runs in debug mode in VS as described in the docs. I also added several log output before/after the moving of files and the deletion of the temp folders in the hope to detect differences in both cases (see lines with >>>>>). Fortunately I was able to reproduce the issue which can be seen in the following screenshot:    

![grafik](https://user-images.githubusercontent.com/5881524/191510941-ddcfd402-59a2-4032-a331-e9f04385ab6d.png)

As can be seen in the failing case (the part below the black line) the temp.2 is somehow deleted, but moving the files has not yet completed. There is no "...>>>>> Finished moving files..." line like it can be seen in the upper (successful) case.

I were unfortunately not able to fix this behavior, but maybe this info gives you some important hints.

**Comment by Energizer188** [comment] 2022-12-02 08:54
I stumble onto the same problem yesterday, several times in a row. I believe it has something to do with our antivirus interfering with the process. I've restarted my computer and the problem was gone.
Do you sign your files? I think that might help to keep our antivirus out of it. (in my cases files were not signed).

**Comment by sebaJoSt** [comment] 2023-02-08 19:35
I have the same problem now, when I install and when I update. No antivirus software besides Windows Defender is running. 

Installing:
![Capture2](https://user-images.githubusercontent.com/388152/217633056-873e6c46-64d4-4371-b4b4-acef3a8ad049.JPG)

Updating:
![Capture](https://user-images.githubusercontent.com/388152/217633077-88361323-d792-4f9c-b12a-0da1df308f42.JPG)

**Comment by JobaDiniz** [comment] 2023-04-26 15:58
I had the same problem with the new version of Clowd.Squirrel. The exact same message box from @sebaJoSt. By running the _setup_ as **admin** the problem went away.

**Comment by sebaJoSt** [comment] 2023-04-26 17:40
Hey, I'm also on 3.0.210-g5f9f594.

**Comment by misterio955** [comment] 2023-07-18 09:17
I had the same problem. It turned out that the antivirus was deleting the temp folder, before it was copied.

**Comment by ethranes** [comment] 2023-08-03 13:53
We have this on version

3.0.210+5f9f594

We do have antivirus, turning it off isn't really an option though

**Comment by misterio955** [comment] 2023-08-03 13:58
> We have this on version
> 
> 3.0.210+5f9f594
> 
> We do have antivirus, turning it off isn't really an option though

You can add policies to your antivirus that will ignore the squirrel temp folder

**Comment by caesay** [comment] 2023-11-15 15:27
I am planning on fixing this on v3 by removing Squirrel's need to use a temp folder at all. This will likely not be backported to v2 due to the scale of the changes.

**Comment by caesay** [comment] 2023-12-26 21:00
This is fixed in v4

**Closed by caesay** 2023-12-26 21:00 UTC
Labels: bug, os:windows
